; Seelie Desktop Pet — Inno Setup script
; Compile with: ISCC.exe /DSrcDir=<staging> /DAppVersion=<x.y.z> seelie.iss
;
; Layout assumptions:
;   {#SrcDir} contains the same flat tree QtIFW's installer_stage produces:
;       Seelie.exe, Qt6*.dll, Live2DCubismCore.dll, plugins/, assets/...
;   This is generated by `cmake --build build --target installer_stage` and
;   ends up at installer/packages/im.cheng.seelie.desktop/data/.
;
;   {#ProjectRoot} is the repo root — used to find LICENSE, the .ico, and
;   to write the output .exe into build/. Passed in by build_inno.py.

#ifndef SrcDir
  #error SrcDir not defined. Pass /DSrcDir=<path> to ISCC.
#endif
#ifndef ProjectRoot
  #error ProjectRoot not defined. Pass /DProjectRoot=<path> to ISCC.
#endif
#ifndef AppVersion
  #define AppVersion "1.0.0"
#endif

#define AppName "Seelie"
#define AppPublisher "HUANG Cheng"
#define AppURL "https://github.com/huangcheng/Seelie"
#define AppExeName "Seelie.exe"
#define AppId "{{E3F8C7B4-9A2D-4E5F-B1C8-3D7F2A8E9C4B}"
#define AppCopyright "Copyright (C) 2026 HUANG Cheng"
#define AppDescription "Seelie Desktop Pet"

[Setup]
AppId={#AppId}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}/issues
AppUpdatesURL={#AppURL}/releases
AppCopyright={#AppCopyright}
; SetupSeelie.exe (the installer itself) gets these fields embedded in its
; own VERSIONINFO block, so right-clicking it in Explorer shows real metadata
; instead of generic "Setup". Mirrors what assets/seelie.rc.in writes into
; the application Seelie.exe.
VersionInfoVersion={#AppVersion}
VersionInfoCompany={#AppPublisher}
VersionInfoCopyright={#AppCopyright}
VersionInfoDescription={#AppDescription} Setup
VersionInfoProductName={#AppDescription}
VersionInfoProductVersion={#AppVersion}
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
LicenseFile={#ProjectRoot}\LICENSE
OutputDir={#ProjectRoot}\build
OutputBaseFilename=SeelieSetup-{#AppVersion}
SetupIconFile={#ProjectRoot}\assets\seelie.ico
UninstallDisplayIcon={app}\{#AppExeName}
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
WizardSizePercent=120
WizardResizable=yes

; Branding — wizard images shown on Welcome/Finish + every other page
WizardImageFile=branding\wizard-image.bmp,branding\wizard-image@2x.bmp
WizardSmallImageFile=branding\wizard-small-image.bmp,branding\wizard-small-image@2x.bmp
WizardImageStretch=yes
WizardImageAlphaFormat=defined

; Per-user OR per-machine — user picks at install time. No code; Inno's
; built-in dialog handles everything. Big UX win over QtIFW.
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog

ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
MinVersion=10.0.17763
ChangesAssociations=no

[Code]
{ Persona-5 inspired installer theming — orange accent on white,
  sharp corners, bold typography. Applied after the wizard form is created. }

const
  PERSONA_ORANGE = $001A6FF3;  { #F36F1A in BGR }
  NEAR_BLACK     = $001A1A1A;
  GRAY_SECONDARY = $00888888;

procedure InitializeWizard();
var
  WelcomeLabel2: TNewStaticText;
begin
  { Increase wizard size for a more spacious, modern feel }
  WizardForm.ClientWidth := ScaleX(600);
  WizardForm.ClientHeight := ScaleY(420);

  { White background, clean typography }
  WizardForm.Color := clWhite;
  WizardForm.Font.Name := 'Segoe UI';
  WizardForm.Font.Size := 9;
  WizardForm.Font.Color := NEAR_BLACK;

  { --- Welcome Page styling --- }
  if WizardForm.WelcomeLabel1 <> nil then
  begin
    WizardForm.WelcomeLabel1.Font.Name := 'Segoe UI';
    WizardForm.WelcomeLabel1.Font.Size := 16;
    WizardForm.WelcomeLabel1.Font.Style := [fsBold];
    WizardForm.WelcomeLabel1.Font.Color := NEAR_BLACK;
  end;

  { Replace the default WelcomeLabel2 with our own for full control }
  if WizardForm.WelcomeLabel2 <> nil then
  begin
    WizardForm.WelcomeLabel2.Caption :=
      'Welcome to Seelie — your new desktop companion.' + #13#10#13#10 +
      'Seelie is a lightweight, frameless desktop pet that reacts to your ' +
      'AI coding tools in real time. Watch her wave when you start a session, ' +
      'cheer when you complete a task, and celebrate your wins with sparkle effects.' + #13#10#13#10 +
      'Features included:' + #13#10 +
      '  • Real-time reactions to Claude Code, Codex, OpenCode & more' + #13#10 +
      '  • 10+ built-in character packs (pets, mascots, anime characters)' + #13#10 +
      '  • Gaming Mode — auto-hides when fullscreen apps are detected' + #13#10 +
      '  • Tip bubbles with contextual coding advice' + #13#10 +
      '  • TTS voice feedback (optional)' + #13#10 +
      '  • Under 10 MB RAM footprint' + #13#10#13#10 +
      'Click Next to begin the installation.';
    WizardForm.WelcomeLabel2.Font.Name := 'Segoe UI';
    WizardForm.WelcomeLabel2.Font.Size := 9;
    WizardForm.WelcomeLabel2.Font.Color := GRAY_SECONDARY;
  end;

  { --- Finish page styling --- }
  if WizardForm.FinishedLabel <> nil then
  begin
    WizardForm.FinishedLabel.Font.Name := 'Segoe UI';
    WizardForm.FinishedLabel.Font.Size := 16;
    WizardForm.FinishedLabel.Font.Style := [fsBold];
    WizardForm.FinishedLabel.Font.Color := NEAR_BLACK;
  end;

  if WizardForm.FinishedHeadingLabel <> nil then
  begin
    WizardForm.FinishedHeadingLabel.Font.Name := 'Segoe UI';
    WizardForm.FinishedHeadingLabel.Font.Size := 9;
    WizardForm.FinishedHeadingLabel.Font.Color := GRAY_SECONDARY;
  end;
end;

{ Keep the Next button looking like a primary action across all pages }
procedure CurPageChanged(CurPageID: Integer);
begin
  WizardForm.NextButton.Font.Style := [fsBold];
  WizardForm.NextButton.Font.Color := clWhite;
  WizardForm.NextButton.Color := PERSONA_ORANGE;

  WizardForm.BackButton.Color := clWhite;
  WizardForm.BackButton.Font.Color := NEAR_BLACK;

  WizardForm.CancelButton.Color := clWhite;
  WizardForm.CancelButton.Font.Color := NEAR_BLACK;
end;

[Languages]
; First-listed is the default. Inno auto-shows a language picker dialog at
; startup whenever 2+ languages are listed, before any wizard page. Users
; pick once; the entire wizard chrome and our [Messages] entries flip
; consistently. No process restart needed (Inno's i18n is single-process).
;
; ChineseSimplified.isl is vendored locally — Inno Setup 6.7.1 ships only
; ~28 official languages; Chinese is community-maintained and lives at
; jrsoftware/issrc:Files/Languages/Unofficial/. We pin a copy here.
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "schinese"; MessagesFile: "ChineseSimplified.isl"

[Messages]
; Override a few wizard chrome strings with product-specific phrasing.
; Note: The detailed welcome text is set programmatically in [Code] above.
; These overrides serve as fallbacks and for the language-picker chrome.
english.WelcomeLabel2=This will install [name/ver] on your computer.%n%nA tiny desktop pet that reacts to your AI coding tool events. Lightweight, frameless, always-on-top.%n%nClick Next to see features and begin installation.
schinese.WelcomeLabel2=即将在您的电脑上安装 [name/ver]。%n%nSeelie 是一个轻量级桌面宠物，会响应您的 AI 编程工具事件。无边框、置顶显示，约 10MB 内存占用。%n%n点击「下一步」查看功能介绍并开始安装。

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "autostart"; Description: "{cm:AutoStartTask}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[CustomMessages]
english.AutoStartTask=Launch Seelie automatically at Windows startup
schinese.AutoStartTask=开机时自动启动 Seelie
english.LaunchAfterInstall=Launch {#AppName}
schinese.LaunchAfterInstall=立即启动 {#AppName}

[Files]
; All app payload from the staged dir, recursed. recursesubdirs + ignoreversion
; means we don't re-version-check Qt DLLs (always overwrite for upgrades).
Source: "{#SrcDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExeName}"
Name: "{group}\{cm:UninstallProgram,{#AppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; Tasks: desktopicon

[Registry]
; Optional auto-start — only created if the user ticked the task. Per-user
; HKCU\...\Run (no admin needed). Removed on uninstall via uninsdeletevalue.
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; \
    ValueType: string; ValueName: "{#AppName}"; ValueData: """{app}\{#AppExeName}"""; \
    Tasks: autostart; Flags: uninsdeletevalue

[Run]
; Optional launch-after-install (the standard Inno checkbox on the Finish page).
Filename: "{app}\{#AppExeName}"; Description: "{cm:LaunchAfterInstall}"; \
    Flags: nowait postinstall skipifsilent
